#
# Looks for NNLS package
#

message("NNLS_DIR:" ${NNLS_DIR})
IF(NNLS_DIR)
    SET(NNLS_INC_DIRS ${NNLS_DIR})
    SET(NNLS_LIB_DIRS ${NNLS_DIR})

    INCLUDE_DIRECTORIES(${NNLS_INC_DIRS})

    FIND_LIBRARY(AUX_NNLS nnls ${NNLS_LIB_DIRS} NO_DEFAULT_PATH)
    
    IF(AUX_NNLS)
        SET(NNLS_LIBRARIES ${AUX_NNLS})
        SET(NNLS_FOUND TRUE)
    ELSE()
        SET(NNLS_FOUND FALSE)
    ENDIF()
ELSE()
    SET(NNLS_FOUND FALSE)
ENDIF()

