//  see finite_cell_application/LICENSE.txt
//
//   Project Name:        Kratos
//   Last Modified by:    $Author: hbui $
//   Date:                $Date: Feb 7, 2017 $
//   Revision:            $Revision: 1.0 $
//
//

#if !defined(KRATOS_FINITE_CELL_APPLICATION_VARIABLES_H_INCLUDED)
#define KRATOS_FINITE_CELL_APPLICATION_VARIABLES_H_INCLUDED


// System includes
#include <string>
#include <iostream>


// External includes


// Project includes
#include "includes/define.h"
#include "includes/variables.h"
#include "includes/ublas_interface.h"

namespace Kratos
{

    #ifdef SD_APP_FORWARD_COMPATIBILITY
    KRATOS_DEFINE_APPLICATION_VARIABLE( FINITE_CELL_APPLICATION, Matrix, SUBCELL_WEIGHTS )
    KRATOS_DEFINE_APPLICATION_VARIABLE( FINITE_CELL_APPLICATION, double, SUBCELL_DOMAIN_SIZE )
    KRATOS_DEFINE_APPLICATION_VARIABLE( FINITE_CELL_APPLICATION, Vector, SUBCELL_DOMAIN_SIZES )
    KRATOS_DEFINE_APPLICATION_VARIABLE( FINITE_CELL_APPLICATION, Vector, PHYSICAL_INTEGRATION_POINT_THREED_STRESSES )
    KRATOS_DEFINE_3D_APPLICATION_VARIABLE_WITH_COMPONENTS(FINITE_CELL_APPLICATION, PHYSICAL_INTEGRATION_POINT_LOCAL)
    KRATOS_DEFINE_3D_APPLICATION_VARIABLE_WITH_COMPONENTS(FINITE_CELL_APPLICATION, PHYSICAL_INTEGRATION_POINT_GLOBAL)
    KRATOS_DEFINE_3D_APPLICATION_VARIABLE_WITH_COMPONENTS(FINITE_CELL_APPLICATION, PHYSICAL_INTEGRATION_POINT_DISPLACEMENT)
    KRATOS_DEFINE_APPLICATION_VARIABLE( FINITE_CELL_APPLICATION, int, OTHER_NODE_ID )
    KRATOS_DEFINE_APPLICATION_VARIABLE( FINITE_CELL_APPLICATION, int, OTHER_ID )
    KRATOS_DEFINE_APPLICATION_VARIABLE( FINITE_CELL_APPLICATION, int, NUMBER_OF_PHYSICAL_POINTS )
    #else
    KRATOS_DEFINE_VARIABLE( Matrix, SUBCELL_WEIGHTS )
    KRATOS_DEFINE_VARIABLE( double, SUBCELL_DOMAIN_SIZE )
    KRATOS_DEFINE_VARIABLE( Vector, SUBCELL_DOMAIN_SIZES )
    KRATOS_DEFINE_VARIABLE( Vector, PHYSICAL_INTEGRATION_POINT_THREED_STRESSES )
    KRATOS_DEFINE_3D_VARIABLE_WITH_COMPONENTS(PHYSICAL_INTEGRATION_POINT_LOCAL)
    KRATOS_DEFINE_3D_VARIABLE_WITH_COMPONENTS(PHYSICAL_INTEGRATION_POINT_GLOBAL)
    KRATOS_DEFINE_3D_VARIABLE_WITH_COMPONENTS(PHYSICAL_INTEGRATION_POINT_DISPLACEMENT)
    KRATOS_DEFINE_VARIABLE( int, OTHER_NODE_ID )
    KRATOS_DEFINE_VARIABLE( int, OTHER_ID )
    KRATOS_DEFINE_VARIABLE( int, NUMBER_OF_PHYSICAL_POINTS )
    #endif

} // namespace Kratos

#endif // KRATOS_FINITE_CELL_APPLICATION_VARIABLES_H_INCLUDED defined

